### ISSUE TITLE
[SCRIPT] - Faction Filter Data Save

### ISSUE THREAD

**Issue by baarsik** [cryosis7/torn_userscripts#9]
Current faction filter is not saved on page refresh, which makes it inefficient to refresh the member list. You have to refresh the page and set the filters once again. Ideally that would be a "Refresh" button or the script should save its data on page switch.

**Comment by cryosis7** [comment]
https://i.imgur.com/E2oBYao.gifv
Are you sure it doesn't happen? It's meant to and does for me
